connector:
    name: Dnd Google Shopping Connector
    jobs:
        csv_google_categories_import:
            title: dnd_google_shopping_connector.jobs.csv_google_categories_import.title
            type:  import
            steps:
                import_google_categories:
                    title: dnd_google_shopping_connector.jobs.csv_google_categories_import.import.title
                    services:
                        reader:    pim_connector.reader.file.google_category
                        processor: pim_connector.processor.denormalization.category.flat
                        writer:    pim_connector.writer.doctrine.category
                    parameters:
                        batch_size: 10

