connector:
    name: Dnd Google Shopping Connector
    jobs:
        csv_google_categories_import:
            title: dnd_google_shopping_connector.jobs.csv_google_categories_import.title
            type:  import
            steps:
                import_google_categories:
                    title: dnd_google_shopping_connector.jobs.csv_google_categories_import.import.title
                    services:
                        reader:    pim_connector.reader.file.google_category
                        processor: pim_connector.processor.denormalization.category.flat
                        writer:    pim_connector.writer.doctrine.category
                    parameters:
                        batch_size: 10

        xml_product_export:
            title: dnd_google_shopping_connector.jobs.xml_product_export.title
            type:  export
            steps:
                export:
                    title:     dnd_google_shopping_connector.jobs.xml_product_export.export.title
                    services:
                        reader:    pim_base_connector.reader.doctrine.product
                        processor: dnd_google_shopping_connector.processor.product_to_flat_array
                        writer:    dnd_google_shopping_connector.writer.file.xml_product
                    parameters:
                        batch_size: 10
