parameters:
    dnd_google_shopping_connector.rest.category.controller.class: Dnd\Bundle\GoogleShoppingConnectorBundle\Controller\Rest\CategoryController
    dnd_google_shopping_connector.rest.attribute.controller.class: Dnd\Bundle\GoogleShoppingConnectorBundle\Controller\Rest\AttributeController
    dnd_google_shopping_connector.rest.currency.controller.class: Dnd\Bundle\GoogleShoppingConnectorBundle\Controller\Rest\CurrencyController
services:
    dnd_google_shopping_connector.rest.category.controller:
        class: '%dnd_google_shopping_connector.rest.category.controller.class%'
        parent: pim_enrich.controller.rest.category
    dnd_google_shopping_connector.rest.attribute.controller:
        class: '%dnd_google_shopping_connector.rest.attribute.controller.class%'
        parent: pim_enrich.controller.rest.attribute
    dnd_google_shopping_connector.rest.currency.controller:
        class: '%dnd_google_shopping_connector.rest.currency.controller.class%'
        parent: pim_enrich.controller.rest.currency