parameters:
    pim_enrich.form.type.category.class: Dnd\Bundle\GoogleShoppingConnectorBundle\Form\Type\CategoryType
    pim_enrich.view_element.category.tab.property.template: 'DndGoogleShoppingConnectorBundle:CategoryTree:Tab/property.html.twig'

services:
    google_shopping_connector_custom.form.type.google_category:
        class: Dnd\Bundle\GoogleShoppingConnectorBundle\Form\Type\GoogleCategoryType
        arguments:
            - %google_shopping_connector.entity.google_category.class%
            - %google_shopping_connector.entity.google_category_translation.class%
        tags:
            - { name: form.type, alias: google_shopping_connector_enrich_google_category }
