parameters:
    dnd_google_shopping_connector.job.job_parameters.constraint_collection_provider.google_category_xlsx_import.class: Dnd\Bundle\GoogleShoppingConnectorBundle\Job\JobParameters\ConstraintCollectionProvider\GoogleCategoryXlsxImport
    dnd_google_shopping_connector.job.job_parameters.constraint_collection_provider.product_xml_export.class: Dnd\Bundle\GoogleShoppingConnectorBundle\Job\JobParameters\ConstraintCollectionProvider\ProductXmlExport
services:
    dnd_google_shopping_connector.job.job_parameters.constraint_collection_provider.google_category_xlsx_import:
        class: '%dnd_google_shopping_connector.job.job_parameters.constraint_collection_provider.google_category_xlsx_import.class%'
        arguments:
            -
                - 'google_shopping_xlsx_category_import'
        tags:
            - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }

    dnd_google_shopping_connector.job.job_parameters.constraint_collection_provider.product_xml_export:
        class: '%dnd_google_shopping_connector.job.job_parameters.constraint_collection_provider.product_xml_export.class%'
        arguments:
            - '@pim_connector.job.job_parameters.constraint_collection_provider.simple_csv_export'
            -
                - 'google_shopping_xml_product_export'
        tags:
            - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }