parameters:
    dnd_google_shopping_connector.connector_name: 'Dnd Google Shopping Connector'
    dnd_google_shopping_connector.job_name.xlsx_google_shopping_category_import: 'google_shopping_xlsx_category_import'
    dnd_google_shopping_connector.job_name.xml_product_export: 'google_shopping_xml_product_export'

services:
    dnd_google_shopping_connector.job.xlsx_google_shopping_category_import:
            class: '%pim_connector.job.simple_job.class%'
            arguments:
                - '%dnd_google_shopping_connector.job_name.xlsx_google_shopping_category_import%'
                - '@event_dispatcher'
                - '@akeneo_batch.job_repository'
                -
                    - '@dnd_google_shopping_connector.step.xlsx_google_category.import'
            tags:
                - { name: akeneo_batch.job, connector: '%dnd_google_shopping_connector.connector_name%', type: '%pim_connector.job.import_type%' }
    dnd_google_shopping_connector.job.xml_product_export:
            class: '%pim_connector.job.simple_job.class%'
            arguments:
                - '%dnd_google_shopping_connector.job_name.xml_product_export%'
                - '@event_dispatcher'
                - '@akeneo_batch.job_repository'
                -
                    - '@dnd_google_shopping_connector.step.xml_product.export'
            tags:
                - { name: akeneo_batch.job, connector: '%dnd_google_shopping_connector.connector_name%', type: '%pim_connector.job.export_type%' }