parameters:
    dnd_google_shopping_connector.reader.file.xlsx.google_category.class: Dnd\Bundle\GoogleShoppingConnectorBundle\Connector\Reader\File\Xlsx\GoogleCategoryReader
services:
    dnd_google_shopping_connector.reader.file.xlsx.google_category:
        class: '%dnd_google_shopping_connector.reader.file.xlsx.google_category.class%'
        arguments:
            - '@pim_connector.reader.file.xlsx_iterator_factory'
            - '@pim_connector.array_converter.flat_to_standard.category'
            - []
            - '@pim_catalog.repository.locale'