parameters:
     pim_connector.reader.file.google_category.class: Dnd\Bundle\GoogleShoppingConnectorBundle\Reader\File\GoogleShoppingCategoryCsvReader

services:
    pim_connector.reader.file.google_category:
        class: %pim_connector.reader.file.google_category.class%
        parent: 'pim_connector.reader.file.csv'
