parameters:
    pim_connector.reader.file.xlsx.google_category.class: Dnd\Bundle\GoogleShoppingConnectorBundle\Reader\File\Xlsx\GoogleCategoryReader

services:
    pim_connector.reader.file.xlsx.google_category:
        class: %pim_connector.reader.file.xlsx.google_category.class%
        parent: pim_connector.reader.file.xlsx_category
