config:
    config:
        pim/fetcher-registry:
            fetchers:
                categories-list:
                    module: pim/base-fetcher
                    options:
                        urls:
                            list: pim_google_shopping_category_rest_index
                attributes-list:
                    module: pim/base-fetcher
                    options:
                        urls:
                            list: pim_google_shopping_attribute_rest_index
                currencies-list:
                    module: pim/base-fetcher
                    options:
                        urls:
                            list: pim_google_shopping_currency_rest_index
    paths:
        categories-list: dndgoogleshoppingconnector/js/categories-list
        attributes-list: dndgoogleshoppingconnector/js/attributes-list
        currencies-list: dndgoogleshoppingconnector/js/currencies-list