parameters:
    dnd_google_shopping_connector.writer.file.xml_product.class: Dnd\Bundle\GoogleShoppingConnectorBundle\Writer\File\Xml\XmlProductWriter

services:
    dnd_google_shopping_connector.writer.file.xml_product:
        class: %dnd_google_shopping_connector.writer.file.xml_product.class%
        arguments:
            - '@akeneo_buffer.factory.array_buffer'
            - '@pim_catalog.repository.attribute'
            - '@pim_catalog.repository.locale'
            - '@pim_catalog.repository.currency'
            - '@akeneo_file_storage.repository.file_info'
