extensions:
    google-shopping-xlsx-category-import-edit:
        module: pim/form/common/edit-form

    google-shopping-xlsx-category-import-edit-main-image:
        module: pim/form/common/main-image
        parent: google-shopping-xlsx-category-import-edit
        targetZone: main-image
        config:
            path: bundles/pimui/images/illustration-import-xlsx.svg

    google-shopping-xlsx-category-import-edit-user-navigation:
        module: pim/menu/user-navigation
        parent: google-shopping-xlsx-category-import-edit
        targetZone: user-menu
        config:
            userAccount: pim_menu.user.user_account
            logout: pim_menu.user.logout

    google-shopping-xlsx-category-import-edit-breadcrumbs:
        module: pim/common/breadcrumbs
        parent: google-shopping-xlsx-category-import-edit
        targetZone: breadcrumbs
        config:
            tab: pim-menu-imports

    google-shopping-xlsx-category-import-edit-cache-invalidator:
        module: pim/cache-invalidator
        parent: google-shopping-xlsx-category-import-edit
        position: 1000

    google-shopping-xlsx-category-import-edit-tabs:
        module: pim/form/common/form-tabs
        parent: google-shopping-xlsx-category-import-edit
        targetZone: content
        position: 100

    google-shopping-xlsx-category-import-edit-properties:
        module: pim/job/common/edit/properties
        parent: google-shopping-xlsx-category-import-edit-tabs
        aclResourceId: pim_importexport_export_profile_property_edit
        targetZone: container
        position: 100
        config:
            tabTitle: pim_enrich.form.job_instance.tab.properties.title
            tabCode: pim-job-instance-properties

    google-shopping-xlsx-category-import-edit-global:
        module: pim/job/common/edit/properties
        parent: google-shopping-xlsx-category-import-edit-tabs
        aclResourceId: pim_importexport_export_profile_property_edit
        targetZone: container
        position: 120
        config:
            tabTitle: pim_enrich.export.product.global_settings.title
            tabCode: pim-job-instance-global

    google-shopping-xlsx-category-import-edit-history:
        module: pim/common/tab/history
        parent: google-shopping-xlsx-category-import-edit-tabs
        targetZone: container
        aclResourceId: pim_importexport_import_profile_history
        position: 130
        config:
            class: Akeneo\Component\Batch\Model\JobInstance
            title: pim_enrich.form.job_instance.tab.history.title
            tabCode: pim-job-instance-history

    google-shopping-xlsx-category-import-edit-properties-code:
        module: pim/job/common/edit/field/text
        parent: google-shopping-xlsx-category-import-edit-properties
        position: 100
        targetZone: properties
        config:
            fieldCode: code
            label: pim_enrich.form.job_instance.tab.properties.code.title
            readOnly: true

    google-shopping-xlsx-category-import-edit-properties-label:
        module: pim/job/common/edit/field/text
        parent: google-shopping-xlsx-category-import-edit-properties
        position: 110
        targetZone: properties
        config:
            fieldCode: label
            label: pim_enrich.form.job_instance.tab.properties.label.title
            readOnly: false

    google-shopping-xlsx-category-import-edit-properties-file-path:
        module: pim/job/common/edit/field/text
        parent: google-shopping-xlsx-category-import-edit-global
        position: 120
        targetZone: properties
        config:
            fieldCode: configuration.filePath
            readOnly: false
            label: pim_enrich.form.job_instance.tab.properties.file_path.title
            tooltip: pim_enrich.form.job_instance.tab.properties.file_path.help

    google-shopping-xlsx-category-import-edit-properties-file-upload:
        module: pim/job/common/edit/field/switch
        parent: google-shopping-xlsx-category-import-edit-global
        position: 130
        targetZone: properties
        config:
            fieldCode: configuration.uploadAllowed
            readOnly: false
            label: pim_enrich.form.job_instance.tab.properties.upload_allowed.title
            tooltip: pim_enrich.form.job_instance.tab.properties.upload_allowed.help

    google-shopping-xlsx-category-import-edit-properties-master-category:
        module: categories-list
        parent: google-shopping-xlsx-category-import-edit-global
        position: 140
        targetZone: properties
        config:
            fieldCode: configuration.master_category
            readOnly: false
            label: pim_enrich.form.job_instance.tab.properties.master_category.title
            tooltip: pim_enrich.form.job_instance.tab.properties.master_category.help

    google-shopping-xlsx-category-import-edit-properties-suffix-category:
        module: pim/job/common/edit/field/text
        parent: google-shopping-xlsx-category-import-edit-global
        position: 150
        targetZone: properties
        config:
            fieldCode: configuration.suffix_category
            readOnly: false
            label: pim_enrich.form.job_instance.tab.properties.suffix_category.title
            tooltip: pim_enrich.form.job_instance.tab.properties.suffix_category.help

    google-shopping-xlsx-category-import-edit-label:
        module: pim/job/common/edit/label
        parent: google-shopping-xlsx-category-import-edit
        targetZone: title
        position: 100

    google-shopping-xlsx-category-import-edit-meta:
        module: pim/job/common/edit/meta
        parent: google-shopping-xlsx-category-import-edit
        targetZone: meta
        position: 100

    google-shopping-xlsx-category-import-edit-secondary-actions:
        module: pim/form/common/secondary-actions
        parent: google-shopping-xlsx-category-import-edit
        targetZone: buttons
        position: 50

    google-shopping-xlsx-category-import-edit-delete:
        module: pim/job/import/edit/delete
        parent: google-shopping-xlsx-category-import-edit-secondary-actions
        targetZone: secondary-actions
        aclResourceId: pim_importexport_import_profile_remove
        position: 100
        config:
            trans:
                title: confirmation.remove.import_profile
                content: pim_enrich.confirmation.delete_item
                success: flash.job_instance.removed
                failed: error.removing.job_instance
            redirect: pim_importexport_import_profile_index

    google-shopping-xlsx-category-import-edit-save-buttons:
        module: pim/form/common/save-buttons
        parent: google-shopping-xlsx-category-import-edit
        targetZone: buttons
        position: 120

    google-shopping-xlsx-category-import-edit-save:
        module: pim/job-instance-import-edit-form/save
        parent: google-shopping-xlsx-category-import-edit
        targetZone: buttons
        position: 0
        config:
            redirectPath: pim_importexport_import_profile_show

    google-shopping-xlsx-category-import-edit-state:
        module: pim/form/common/state
        parent: google-shopping-xlsx-category-import-edit
        targetZone: state
        position: 900
        config:
            entity: pim_enrich.entity.job_instance.title

    google-shopping-xlsx-category-import-edit-validation:
        module: pim/job/common/edit/validation
        parent: google-shopping-xlsx-category-import-edit
