extensions:
    xlsx-google-shopping-category-import-edit:
        module: pim/form/common/edit-form

    xlsx-google-shopping-category-import-edit-cache-invalidator:
        module: pim/cache-invalidator
        parent: xlsx-google-shopping-category-import-edit
        position: 1000

    xlsx-google-shopping-category-import-edit-tabs:
        module: pim/form/common/form-tabs
        parent: xlsx-google-shopping-category-import-edit
        targetZone: content
        position: 100

    xlsx-google-shopping-category-import-edit-properties:
        module: pim/job/common/edit/properties
        parent: xlsx-google-shopping-category-import-edit-tabs
        aclResourceId: pim_importexport_export_profile_property_edit
        targetZone: container
        position: 100
        config:
            tabTitle: pim_enrich.form.job_instance.tab.properties.title
            tabCode: pim-job-instance-properties

    xlsx-google-shopping-category-import-edit-history:
        module: pim/common/tab/history
        parent: xlsx-google-shopping-category-import-edit-tabs
        targetZone: container
        aclResourceId: pim_importexport_import_profile_history
        position: 120
        config:
            class: Akeneo\Component\Batch\Model\JobInstance
            title: pim_enrich.form.job_instance.tab.history.title
            tabCode: pim-job-instance-history

    xlsx-google-shopping-category-import-edit-properties-code:
        module: pim/job/common/edit/field/text
        parent: xlsx-google-shopping-category-import-edit-properties
        position: 100
        targetZone: properties
        config:
            fieldCode: code
            label: pim_enrich.form.job_instance.tab.properties.code.title
            readOnly: true

    xlsx-google-shopping-category-import-edit-properties-label:
        module: pim/job/common/edit/field/text
        parent: xlsx-google-shopping-category-import-edit-properties
        position: 110
        targetZone: properties
        config:
            fieldCode: label
            label: pim_enrich.form.job_instance.tab.properties.label.title
            readOnly: false

    xlsx-google-shopping-category-import-edit-properties-file-path:
        module: pim/job/common/edit/field/text
        parent: xlsx-google-shopping-category-import-edit-properties
        position: 120
        targetZone: global-settings
        config:
            fieldCode: configuration.filePath
            readOnly: false
            label: pim_enrich.form.job_instance.tab.properties.file_path.title
            tooltip: pim_enrich.form.job_instance.tab.properties.file_path.help

    xlsx-google-shopping-category-import-edit-properties-parent-categories-list:
        module: parent-categories-list
        parent: xlsx-google-shopping-category-import-edit-properties
        position: 130
        targetZone: global-settings
        config:
            fieldCode: configuration.parentCategories
            readOnly: false
            label: dnd_google_shopping_connector.form.job_instance.tab.properties.parent_categories.title
            tooltip: dnd_google_shopping_connector.form.job_instance.tab.properties.parent_categories.help

    xlsx-google-shopping-category-import-edit-properties-file-upload:
        module: pim/job/common/edit/field/switch
        parent: xlsx-google-shopping-category-import-edit-properties
        position: 140
        targetZone: global-settings
        config:
            fieldCode: configuration.uploadAllowed
            readOnly: false
            label: pim_enrich.form.job_instance.tab.properties.upload_allowed.title
            tooltip: pim_enrich.form.job_instance.tab.properties.upload_allowed.help

    xlsx-google-shopping-category-import-edit-label:
        module: pim/job/common/edit/label
        parent: xlsx-google-shopping-category-import-edit
        targetZone: title
        position: 100

    xlsx-google-shopping-category-import-edit-meta:
        module: pim/job/common/edit/meta
        parent: xlsx-google-shopping-category-import-edit
        targetZone: meta
        position: 100

    xlsx-google-shopping-category-import-edit-back-to-grid:
        module: pim/form/common/back-to-grid
        parent: xlsx-google-shopping-category-import-edit
        targetZone: back
        aclResourceId: pim_importexport_import_profile_index
        position: 80
        config:
            backUrl: pim_importexport_import_profile_index

    xlsx-google-shopping-category-import-edit-delete:
        module: pim/job/import/edit/delete
        parent: xlsx-google-shopping-category-import-edit
        targetZone: buttons
        aclResourceId: pim_importexport_import_profile_remove
        position: 100
        config:
            trans:
                title: confirmation.remove.job_instance
                content: pim_enrich.confirmation.delete_item
                success: flash.job_instance.removed
                failed: error.removing.job_instance
            redirect: pim_importexport_import_profile_index

    xlsx-google-shopping-category-import-edit-save-buttons:
        module: pim/form/common/save-buttons
        parent: xlsx-google-shopping-category-import-edit
        targetZone: buttons
        position: 120

    xlsx-google-shopping-category-import-edit-save:
        module: pim/job-instance-import-edit-form/save
        parent: xlsx-google-shopping-category-import-edit
        targetZone: buttons
        position: 0
        config:
            redirectPath: pim_importexport_import_profile_show

    xlsx-google-shopping-category-import-edit-state:
        module: pim/form/common/state
        parent: xlsx-google-shopping-category-import-edit
        targetZone: state
        position: 900
        config:
            entity: pim_enrich.entity.job_instance.title

    xlsx-google-shopping-category-import-edit-validation:
        module: pim/job/common/edit/validation
        parent: xlsx-google-shopping-category-import-edit
