extensions:
    xlsx-google-shopping-category-import-show:
        module: pim/form/common/edit-form

    xlsx-google-shopping-category-import-show-tabs:
        module: pim/form/common/form-tabs
        parent: xlsx-google-shopping-category-import-show
        targetZone: content
        position: 100

    xlsx-google-shopping-category-import-show-upload:
        module: pim/job/common/edit/upload
        parent: xlsx-google-shopping-category-import-show
        aclResourceId: pim_importexport_import_profile_launch
        targetZone: content
        position: 90

    xlsx-google-shopping-category-import-show-properties:
        module: pim/job/common/edit/properties
        parent: xlsx-google-shopping-category-import-show-tabs
        targetZone: container
        position: 100
        config:
            tabTitle: pim_enrich.form.job_instance.tab.properties.title
            tabCode: pim-job-instance-properties

    xlsx-google-shopping-category-import-show-history:
        module: pim/common/tab/history
        parent: xlsx-google-shopping-category-import-show-tabs
        targetZone: container
        aclResourceId: pim_importexport_import_profile_history
        position: 120
        config:
            class: Akeneo\Component\Batch\Model\JobInstance
            title: pim_enrich.form.job_instance.tab.history.title
            tabCode: pim-job-instance-history

    xlsx-google-shopping-category-import-show-properties-code:
        module: pim/job/common/edit/field/text
        parent: xlsx-google-shopping-category-import-show-properties
        position: 100
        targetZone: properties
        config:
            fieldCode: code
            label: pim_enrich.form.job_instance.tab.properties.code.title
            readOnly: true

    xlsx-google-shopping-category-import-show-properties-label:
        module: pim/job/common/edit/field/text
        parent: xlsx-google-shopping-category-import-show-properties
        position: 110
        targetZone: properties
        config:
            fieldCode: label
            label: pim_enrich.form.job_instance.tab.properties.label.title
            readOnly: true

    xlsx-google-shopping-category-import-show-properties-file-path:
        module: pim/job/common/edit/field/text
        parent: xlsx-google-shopping-category-import-show-properties
        position: 120
        targetZone: global-settings
        config:
            fieldCode: configuration.filePath
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.file_path.title
            tooltip: pim_enrich.form.job_instance.tab.properties.file_path.help

    xlsx-google-shopping-category-import-show-properties-parent-categories-list:
        module: parent-categories-list
        parent: xlsx-google-shopping-category-import-show-properties
        position: 130
        targetZone: global-settings
        config:
            fieldCode: configuration.parentCategories
            readOnly: true
            label: dnd_google_shopping_connector.form.job_instance.tab.properties.parent_categories.title
            tooltip: dnd_google_shopping_connector.form.job_instance.tab.properties.parent_categories.help

    xlsx-google-shopping-category-import-show-properties-file-upload:
        module: pim/job/common/edit/field/switch
        parent: xlsx-google-shopping-category-import-show-properties
        position: 140
        targetZone: global-settings
        config:
            fieldCode: configuration.uploadAllowed
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.upload_allowed.title
            tooltip: pim_enrich.form.job_instance.tab.properties.upload_allowed.help

    xlsx-google-shopping-category-import-show-label:
        module: pim/job/common/edit/label
        parent: xlsx-google-shopping-category-import-show
        targetZone: title
        position: 100

    xlsx-google-shopping-category-import-show-meta:
        module: pim/job/common/edit/meta
        parent: xlsx-google-shopping-category-import-show
        targetZone: meta
        position: 100

    xlsx-google-shopping-category-import-show-back-to-grid:
        module: pim/form/common/back-to-grid
        parent: xlsx-google-shopping-category-import-show
        targetZone: back
        aclResourceId: pim_importexport_import_profile_index
        position: 80
        config:
            backUrl: pim_importexport_import_profile_index

    xlsx-google-shopping-category-import-show-edit:
        module: pim/common/redirect
        parent: xlsx-google-shopping-category-import-show
        targetZone: buttons
        position: 100
        config:
            label: pim_enrich.form.job_instance.button.edit.title
            route: pim_importexport_import_profile_edit
            identifier:
                path: code
                name: code

    xlsx-google-shopping-category-import-show-launch:
        module: pim/job/common/edit/upload-launch
        parent: xlsx-google-shopping-category-import-show
        aclResourceId: pim_importexport_import_profile_launch
        targetZone: buttons
        position: 110
        config:
            launch: pim_enrich.form.job_instance.button.import.launch
            upload: pim_enrich.form.job_instance.button.import.upload
            route: pim_enrich_job_instance_rest_import_launch
            identifier:
                path: code
                name: code
