Dnd\Bundle\GoogleShoppingConnectorBundle\Model\ProductValue:
    type: entity
    table: pim_catalog_product_value
    changeTrackingPolicy: DEFERRED_EXPLICIT
    indexes:
        value_idx:
            columns:
                - attribute_id
                - locale_code
                - scope_code
        varchar_idx:
            columns:
                - value_string
        integer_idx:
            columns:
                - value_integer
    manyToOne:
        googleCategory:
            targetEntity: Dnd\Bundle\GoogleShoppingConnectorBundle\Entity\GoogleCategory
            joinColumn:
                name: google_category_id
                referencedColumnName: id
